### ISSUE TITLE
Don't load Kite sidebar panel in empty state

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#107]
I may be missing something, but now that we only show info in the expand panel when the user asks for it (as opposed to as the user clicks around), I don't think we should open the expand panel when Atom first starts, or when the user switches the "Display Expand View As" to sidebar.

I suppose we'll be replacing the "Show sidebar when user clicks on status bar icon" soon with the status panel anyway.

(Are there other times when we open the Expand panel without content?)

**Comment by adamsmith** [comment]
Similarly, I think we should remove the "Toggle Sidebar" and "Open Sidebar" command palette items.

**Comment by abe33** [comment]
> I don't think we should open the expand panel when Atom first starts, or when the user switches the "Display Expand View As" to sidebar.

That's only if you have the `openSidebarOnStartup` setting enabled, which defaults to `false` since sidebar became the default view.

> I suppose we'll be replacing the "Show sidebar when user clicks on status bar icon" soon with the status panel anyway.

Exactly

> Similarly, I think we should remove the "Toggle Sidebar" and "Open Sidebar" command palette items.

I don't think so, having these commands means that users can bind them to their own shortcuts, it' doesn't cost us much and it can also help us to trigger action just by dispatching a command.

**Comment by adamsmith** [comment]
Okay, sounds good!
