### ISSUE TITLE
Hover does not work before edit events

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#118]
For now this is a wont-fix, adding here so that we can track it.

steps to reproduce:
1) open new python file
2) click around in file
3) no responses until edit the file

what is happening in the plugin:
1) open new python file `foo.py`
2) hit kited with a normal event to "prime" kited
3) hit tokens endpoint and get 404 response because the file may not yet loaded into kited
4) since we already received a 404 from the tokens endpoint we no longer trigger requests.
5) user edits file so tokens may have changed, receive 200 from tokens endpoint and hover now works, or user switches to another file then back to `foo.py` and the lost_focus event makes the file active again and we recheck tokens endpoint and get 200.

Current solution -- we try a slight delay between steps 2 and 3 to give kited a chance to track the file, sometimes this works.

Proposed solutions:
1) check whether events endpoint responds with a 200 and in that case if we did not get tokens previously then try to get tokens again -- user has to interact with file to trigger this, not ideal.

Logs:
![screen shot 2017-03-14 at 9 43 22 pm](https://cloud.githubusercontent.com/assets/425691/23933970/4ecf34da-08ff-11e7-9784-aad882276cfe.png)

**Comment by jlozano** [comment]
@abe33 does the above description look correct?

**Comment by adamsmith** [comment]
Also ran into this [independently]

**Comment by abe33** [comment]
Oh sorry for the late reply, so yes that's totally correct.

FWIW we're not making hover and reports requests, or showing context menu, because we rely on tokens to get the char range needed by these calls. Initially I was making these range by looking at the words boundaries in the file, but we were making requests for invalid ranges (like operators, numeric values, words in a string, etc.) and in the end it was not as simple and performant as going with tokens.

I'm thinking that I can probably try to make a request to the `/clientapi/permissions/authorized` endpoint first and then retry the tokens request when it fails with 404 for whitelisted files (200 on the authorized enpoint).
