### ISSUE TITLE
Weird scrolling section for requests.post

### ISSUE THREAD

**Issue by keien** [kiteco/atom-plugin#140]
Is this expected?
![mar-22-2017 13-41-12](https://cloud.githubusercontent.com/assets/1103512/24219794/52d8d57a-0f05-11e7-9fad-936cc6191f6e.gif)

there's a weird scrolling section for parameters, which goes away after I resize the window

**Comment by abe33** [comment]
another weird behaviour of flexbox ¯\_(ツ)_/¯

More seriously, it's definitely not expected, but it's a bit hard for me to explain exactly what's going on, whe have the first part for the documentation that is allowed to shrink as much as needed, and at the same time the content's container can also scroll (because even with no docs the rest can fill up the space). I guess in some circumstances (docs too long, rest too long, not enough vertical space for all) the container will start allowing scroll, but once you have resized it enough the browser judge that it can now use the whole vertical space without scroll and suddenly shrink the docs div.

I can put a `min-height` on the docs so that it won't suddenly collapse like that, but I'm not sure that it'll be better in the end, I just tried hacking it a bit in the devtools and the result was not convincing.

**Comment by jlozano** [comment]
@abe33 can we close this?

**Comment by abe33** [comment]
yup
