### ISSUE TITLE
Definition link has line number in global code nodes

### ISSUE THREAD

**Issue by abmirayo** [kiteco/atom-plugin#147]
@abe33 

In global code nodes, there's a definition link that doesn't work, no file name, and just a file number. 
![image](https://cloud.githubusercontent.com/assets/163122/24325302/3920433e-1153-11e7-9169-0431f776f107.png)

**Comment by abe33** [comment]
I'm not sure that the issue comes from the Atom plugin, as far as I can tell, the only way to get an empty string when calling `path.basename` (which I'm using to display the file name in the definition) is to pass an empty string. I added a safeguard to not render definition if we get an empty file name but that should probably be double-checked at kited level. 

If you can reproduce consistently you can enable the `developer mode` setting and check whether the file name in the definition field is empty or not.
