### ISSUE TITLE
Login UI should handle no-password case more gracefully.

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#17]
The Login UI in the Kite Atom package doesn't handle the no-password-yet case very gracefully.

Steps to access the Login UI are in here: https://github.com/kiteco/atom-plugin/issues/16

More info about the no-password case here: https://github.com/kiteco/kite-installer/issues/26

**Comment by abe33** [comment]
Thinking about it, I would see something like the following:

1. In the login form, once the user has filled the email field we should attempt to know whether he has set a password. As far as I can tell, currently, the only way to do that is by trying to authenticate the user and the checking that the return code is `9`. Ideally we should have a service method to check whether an email has an associated password.
2. Once we have determined that the user has not set his password yet, it'd be great if we could just add a hint below the password field saying that since he has no password yet we'll register one now through this form. But I'm not sure that this is feasible with the current API (@dhung09, @alexflint if you have any clues about that?).
3. If we can't sets his password within Atom we can replace the password field by a link to the place he can set his password.

What's your thought?

**Comment by adamsmith** [comment]
RE #2 and #3, the idea is that we'd like for users to verify their email address, and only then set their password.  This is to prevent someone from signing up saying they're billg@microsoft.com, and then setting up a password under that email.  So if they don't have a password setup yet, and they're trying to login, we'll need to say something like "Click the link in your email verification email to set up your password, then login here.  (<a>resend verification email</a>)"
