### ISSUE TITLE
kwargs displayed even though there are none

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#241]
Windows 10
Atom 1.19.5
Kite 2017-080-31

I invoked the signature info for the function noKwargs() and clicked on the kwargs links (as in the screenshot). I'm not sure where `myKwargs` even comes from, it shouldn't be in the response of the `noKwargs` signature info at all.  

Atom displayed a list of kwargs even though there are none defined. I couldn't debug this on Windows but on Linux Kite returned no kwargs definitions for the code pasted below.

Invoking for 

```python
def noKwargs():
	return 1
def  myKwargs(**myKwargs):
	return 2

noKwargs()
myKwargs()
```
![kwargs-rendering](https://user-images.githubusercontent.com/11473063/30113342-b51ac7f0-9314-11e7-88ae-8964486415ba.png)

**Comment by abe33** [comment]
Hmm, I think the issue does come from `kited`, because, when rendering the signature panel, I'm only using the data received from the signature endpoint (no cache mechanism, no redux-type stores that could leak data from previous calls if not cleared properly) and I build a completely new HTML string from that and completely replace the signature panel content (no risk of remaining elements from previous calls).

What's weird here, is that it seems to mess up three things, the `noKwargs` function has the signature of the `myKwargs` one and the `kwarg_parameters` from JSON.

Also, I don't reproduce that with your sample on OSX, and if you reproduce on linux it might be an issue with the windows version.

**Comment by jansorg** [comment]
@abe33 I was able to reproduce this on Mac and Windows (Linux untested due to missing Atom plugin).  I didn't see this in PyCharm.

It seems to be related to caching, I'm not sure whether it's in Kite or Atom. I don't know to to debug the POST requests in Atom. Could you have a look at this?

Take this code:

```python
import json

def noKwargs():
    return 1

json.dumps()
noKwargs()
```

First invoke signature info of `json.dumps()` and click on the **kw to expand it.
The close the signature panel and invoke the signature info of `noKwargs()` and expand the **kw arg. The kwargs are taken from the previous invocation for unknown reasons.

**Comment by abe33** [comment]
I can reproduce, and I can confirm that it is present in `kited response`.

If you want to see all communication you can increase the verbosity from the plugin settings. In `debug` you'll see all networks calls and with `verbose` you'll have even more details.

**Comment by jansorg** [comment]
This is now a kite issue at https://github.com/kiteco/kiteco/issues/4822
