### ISSUE TITLE
Can't see shortcut for opening docs on Windows

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#309]
![screen shot 2018-02-12 at 10 06 01 am](https://user-images.githubusercontent.com/87728/36111872-7856f20e-0fdc-11e8-869a-0e8e30d52a5b.png)

**Comment by abe33** [comment]
We don't really have control over how the status bar items behaves, it's handled by the theme's css and this one is most likely caused by a combination of flex elements and text overflow. I'm not sure whether to remove the shortcut entirely, shorten the label to let space to the shortcut, use the keyboard symbol instead of the literal key name, or use a tooltip to display the uncut version.

**Comment by adamsmith** [comment]
@dhung09 maybe we could drop the "at cursor"?  (making it shorter would also help with the visual noise issue.)

**Comment by dhung09** [comment]
yeah, i think we can change this to `Kite: Docs available`. i'll update the proposal docs

**Comment by adamsmith** [comment]
Is this merged?
