### ISSUE TITLE
Selection sending focus events

### ISSUE THREAD

**Issue by tarakju** [kiteco/atom-plugin#313]
@abe33 

Moving the cursor around in the same file (unmodified) should be sending `selection` events, but I am currently seeing `focus` events being sent instead. Unsure when this regression happened, but it definitely was working correctly just earlier this week.

**Comment by abe33** [comment]
I don't think this comes from a change on our end. What I observe is that now every click is triggering a `focus` event on the editor despite it already having the focus. That was not the case before. The issue here is that the `focus` event comes immediately after the `selection` one, so in the merge routine we skipping the `selection` event and only sending the `focus` one. When using the keyboard to move the cursor the behaviour is still the one we're expecting.
