### ISSUE TITLE
hover + completions interaction

### ISSUE THREAD

**Issue by dbratz1177** [kiteco/atom-plugin#385]
surfaced during QA, when completions are triggered simultaneously to hovering over a token:
![image](https://user-images.githubusercontent.com/6146901/38953318-3b90cb42-4303-11e8-8b5c-94626c526e4c.png)

Not sure to what degree this is fixable or if this is even something to consider a problem, but wanted to get thoughts 

@abe33 @mwichary

**Comment by mwichary** [comment]
I saw this a few times, too. 

A few ideas:

· as a starting point, hover pop-ups should be on top of typing pop-ups in the z-index sense, since they are more ephemeral. (This is reflected in the redesign by the hover pop-up having bigger shadow  than typing pop-ups.) This will at least not feel broken.

· we might also want to consider a rule that “there can only be one pop-up on the screen”. A typing pop-up should close any hover pop-up visible, and prevent one from showing up as long as the typing pop-up is on the screen. The way to achieve it might be to add a class to the entire document that makes a hover pop-up do ```display: none```, when typing pop-ups show up.

**Comment by dbratz1177** [comment]
I agree with both points - though, on the second, I wonder how many users would intentionally want to see both sources of information simultaneously

The first one, though, I think we should definitely implement.

**Comment by dbratz1177** [comment]
@jansorg sounds good - thanks for pinging me on this and bringing it back to my awareness.

Definitely a UI/UX issue. I'll provisionally assign myself and get to it in the next week or so.

**Comment by adamsmith** [comment]
It probably makes sense for @abe33 to work on this.  (cc @jansorg )

Daniel says when hover or completions are shown, if the other is open then close it first.  So there should only be one visible at a time, and it should be the most-recently-used.
