### ISSUE TITLE
No wrapping in Error Rescue sidebar

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#386]
@mwichary Any thoughts?

This is a bit artificial, but I guess that long method names will be used. Long names don't wrap atm.
![screenshot_20180424_165244](https://user-images.githubusercontent.com/11473063/39195329-e999758c-47df-11e8-9fc7-b6f67e306cca.png)

**Comment by abe33** [comment]
Looks like a `word-break: break-word|break-all` should do the trick

I tend to prefer `break-word` in that case, because I believe a function signature is more likely to wrap because of its arguments than because of the length of its name, and `break-all`, while not wrapping after `def`, is splitting arguments in two rather than wrapping at the comma before.

|`break-all`|`break-word`|
|---|---|
|![errored_py_ ___github_kite](https://user-images.githubusercontent.com/247140/39198004-4672e56c-47e6-11e8-8f66-4ef4f5891a5d.png)|![kite_error_rescue_ ___github_kite](https://user-images.githubusercontent.com/247140/39197969-271c7cdc-47e6-11e8-801c-89b27ef25d35.png)|

**Comment by mwichary** [comment]
Thanks to both of you! I like @abe33’s proposal. I will send a PR.

**Comment by mwichary** [comment]
I fixed this.
