### ISSUE TITLE
Moving mouse outside of Atom on right hand edge -> hover appears

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#421]
Steps to repro:

1) Move your mouse over an identifier, but don't hover.  Instead, move the cursor outside of the Atom window on the _right hand_ edge.

Expected: Hover should not appear

Actual: Hover appears

![may-29-2018 13-55-48](https://user-images.githubusercontent.com/87728/40685110-31a86cce-6348-11e8-8fbb-77e3526245c1.gif)

**Comment by abe33** [comment]
I can reproduce, I think the issue here s that we start a timeout when hovering a word that we'll clear if we move the mouse to a new word (a new text range), in that case, moving the mouse out of the window will stop any mouse events and the way Atom computes mouse coordinate to text coordinates conversion - positions on the remaining line after the last char wrap to the last character position - make us believe we're still in the same range. I'm still not sure whether this can be easily fixed or if this will require much more changes to move the timeout before we make mouse pos->text pos conversions.
