### ISSUE TITLE
Single char completion results in endless loop

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#455]
To reproduce:
```python
a = 1
a‸
```
When the cursor is after `a` and the completion `a` is chosen, the completions list shows up again. The expected behavior is that the completions list should not be shown after the completion is chosen.

**Comment by abe33** [comment]
Actually I'm not even sure that suggesting completions after a first char is the expected behaviour (see 
https://github.com/atom/autocomplete-plus/issues/795). AFAICT there's no consensus for that, some people are annoyed by suggestion shown too early, others don't mind it. 

Also, autocomplete-plus behaviour is to trigger a completion request whenever a single char is inserted, whatever the way that char was inserted (if you `inserText('a')` you will trigger a completion request just like if you typed that char) (see: https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.js#L739).

Anyway, it seems our only option here is to continue with our autocomplete patching, because while we can handle that only in our provider (by storing when we insert a single char to not make suggestions again) this won't prevent other providers to return suggestions.

**Comment by abe33** [comment]
I also just noticed that the suggestions list doesn't show again if the choosed suggestion is not the first one.
