### ISSUE TITLE
No expand panel in latest version

### ISSUE THREAD

**Issue by Tonysssu** [kiteco/atom-plugin#466]
No search overlay in the latest version.
<img width="62" alt="68747470733a2f2f6769746875622e636f6d2f6b697465636f2f61746f6d2d706c7567696e2f626c6f622f6d61737465722f646f63732f696d616765732f6b6974652d6163746976652d7365617263682d636f6c6c61707365642e706e673f7261773d74727565" src="https://user-images.githubusercontent.com/39546387/43306133-f714dc2c-912e-11e8-9c0f-7d14be386c28.png">

can't even trigger expand panel. 
<img width="743" alt="screen shot 2018-07-26 at 11 45 23 pm" src="https://user-images.githubusercontent.com/39546387/43305990-7f6cbb36-912e-11e8-8237-b6388e1b067a.png">

Tried to reinstall Kite but doesn't help.

**Comment by dhung09** [comment]
Hi @Tonysssu 

Thanks for your inquiry into this matter. This decision wasn't made lightly so I wanted to provide an in-depth explanation for the product change.

__TL;DR__ - We made the tough decision to discontinue support for documentation inside the editor so that we could focus our efforts on providing the very best Python autocompletions.

As you might know, Kite integrates with 5 different editors. Getting any feature right in a single editor is hard enough, and getting it right in 5 editors is at least 5 times as hard. Given our small team size, we needed to figure out how to utilize our time more appropriately and when we thought about which features would create the most value for our users going forward, it became clear that developing smarter and more context-aware autocompletions would be much more transformative in the long run than maintaining documentation in the editor. We're currently investing a lot of resources into improving our static analysis and machine learning models, and we're very excited at the prospect of shipping more advanced autocompletions for our users.

In the meantime, documentation will still be available in the Copilot and in our Webdocs. While we've also poured a lot of time and effort into these 2 products, we realize that they may not be perfect replacements and we sincerely apologize for the inconvenience. However, we remain committed to our mission of building tools to help you code more efficiently and we're confident our increased investment in AI-powered autocompletions will prove to be useful to you in the coming months.

If you'd like to provide more thoughts on this matter, please feel free to email feedback@kite.com.
