### ISSUE TITLE
"Kite is ready" displayed when Kite isn't installed

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#497]
Windows 10 Pro
Fresh user account (local admin)

- opened python file
- This was displayed when I hoverd with the mouse cursor on the kite icon:
![atom-kite-read-uninstalled](https://user-images.githubusercontent.com/11473063/46024707-a996a280-c0e7-11e8-99f9-4bf7bb8a2f08.png)

**Comment by abe33** [comment]
I do not reproduce, currently the only case where we display this tooltip when kite is not in a normal state is when we're not in a supported file. I can see in the specs we're expecting no messages for unsupported files, so that is still something I can change. But for the issue at hand, is it possible that the python file was not the active file or that you had a different grammar applied to that file?

**Comment by jansorg** [comment]
I was able to reproduce this, this seems to happen only for unsupported files, as you already assumed.
I think the spec says that "Kite: Not Installed" should always be displayed, even for unsupported files, see the first row at https://kite.quip.com/rVcJA1bIqZny/Kite-Status-Spec#s:QcWACAFQV04;QcWACAE4DQl

**Comment by abe33** [comment]
Was fixed with #499

**Comment by 9994444ggg** [comment]
Thank You was Helpfull
