### ISSUE TITLE
events for "used completion returned by Jedi but not Kite (whitelisted filepath)" reported after removing whitelisted directory through sidebar

### ISSUE THREAD

**Issue by keien** [kiteco/atom-plugin#54]
To reproduce:

1. Be in a whitelisted file in atom
1. Remove whitelisted directory from whitelist in the Kite sidebar settings tab - Kite sidebar will show the "not whitelisted" message but atom will not
1. Use a completion in atom and check Mixpanel - the reported event will be "used completion returned by Jedi but not Kite (whitelisted filepath)"
1. Restart atom - atom will now show the "not whitelisted" message
1. Use a completion - this time it will be the correct "atom kite+acp - used completion returned by Jedi but not Kite (not-whitelisted filepath)" one

**Comment by abe33** [comment]
Yes, this is because we don't check the whitelisting of a path on each completions request.
Actually testing if a path is whitelisted involves many steps that are IMO too costly to be triggered on each keystroke (which is what completions is doing): 
- testing whether Kite is supported, 
- testing that Kite is installed
- testing that Kite is running
- testing that Kite is reachable
- testing that the user is authenticated
- finally testing that the path is whitelisted.

**Comment by adamsmith** [comment]
good point; let me talk with Keien and possibly Tarak to figure out the right way to collect this metric that doesn't involve the whitelisting check, which I agree is a bit too convoluted.
