### ISSUE TITLE
Scroll Past End Resets After App Close

### ISSUE THREAD

**Issue by paulcruse3** [kiteco/atom-plugin#631]
Description
Your plugin causes the Scroll Past End setting in ("Settings -> Editor") to reset.

When I close atom and re-open it, Scroll Past End is enabled again (if your package is enabled).

This does not occur when in safe mode or if I return it to factory settings. 

Steps to Reproduce
Use version 1.40.1 (on Mac)
Install your Kite Plugin
Go to "Settings -> Editor" and uncheck "Scroll Past End"
Close Atom and ReOpen (doesn't stick)
(TO CHECK IT WORKS)
Disable Kite, then uncheck and restart (it works)

Expected behavior:

I expect Scroll Past End checkbox to remain unchecked even after closing Atom even when using Kite

Actual behavior:

Scroll Past End Resets After App Close

Reproduces how often:

This happens every time

Versions
Mac 10.14.6
Atom 1.40.1

**Comment by metalogical** [comment]
Hi @paulcruse3 

Our plugin enables the scroll past end setting due to our inline StackOverflow search functioning better with that setting enabled.

In retrospect, this does seem too aggressive. Instead, we will check if the setting is disabled, and if so, suggest to the user that enabling it would improve the Kite user experience.
